name: "Sample Pipeline"

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:

  - job: Job
    displayName: "Job"
    steps:

      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - task: Bash@3
        displayName: "Bash"
        inputs:
          targetType: "inline"
          script: |
            echo Bash

      - task: PowerShell@2
        displayName: "PowerShell"
        inputs:
          targetType: "inline"
          script: |
            echo PowerShell
