name: test

on: [push, pull_request]

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...